### ISSUE TITLE
Issue template for feature request missing.

### ISSUE THREAD

**Issue by shubhankarsharma00** [CircuitVerse/cv-frontend#24]
**Describe the bug**
Check the issue templates at Circuitverse's main repo and add a similar template for the feature requests.

**Comment by shubhankarsharma00** [comment]
Only for first-timers.

**Comment by shubhamgoel24** [comment]
Hello, can I work on this ?
Also where is the template for feature request in main repo, because I can't find it.

**Comment by shubhamgoel24** [comment]
Ok now got it. 
So exact feature request template have to be made ?

**Comment by yuktibagrodia** [comment]
Can I do it? @shubhankarsharma00

**Comment by yuktibagrodia** [comment]
done check @shubhankarsharma00
  #27

**Comment by surajat17** [comment]
@yuktibagrodia i have already opened a pr 15 days ago.

**Comment by yuktibagrodia** [comment]
My bad @surajat17

**Comment by yuktibagrodia** [comment]
Any other help i can do ? @shubhankarsharma00

**Comment by shubhankarsharma00** [comment]
@yuktibagrodia I don't have any particular issue in mind right now. We have to update this whole repo with the Ciruitverse's new_UI branch once the next version is finalized.
