### ISSUE TITLE
On click of search button the heading "Dive into the world of Logic" gets hidden!!!

### ISSUE THREAD

**Issue by khanjasir90** [CircuitVerse/cv-frontend#28]
Description : When you click on the search button on the home page the search bar hides the heading "Dive into the world of Logic"

**To Reproduce**
1. Go to the home page of circuitverse.org
2. Click on search button icon
3. on the click of the button the search bar hides the line of user interface "Dive into the world of Logic".

**Expected behavior**
The line "Dive into the world of Logic" should not get hide else it should be visible to the user.

**Screenshots**
Before : 
![before](https://user-images.githubusercontent.com/53305380/96356607-8ac03a00-110e-11eb-9cad-30b4d27eebfb.PNG)
After : 
![after](https://user-images.githubusercontent.com/53305380/96356611-9ad81980-110e-11eb-87e1-8100b4f50fb4.PNG)

**Additional context**

**Are you working on this issue? (Yes/No)**
Yes!!!

**Comment by khanjasir90** [comment]
I would like to work on this!!! kindly assign it to me!

**Comment by shubhankarsharma00** [comment]
@khanjasir90 this is actually not meant for this repository. The name is a bit confusing but cv-fronted is actually only the simulator part. You should open this issue in the Circuitverse repo.

**Comment by khanjasir90** [comment]
okay @shubhankarsharma00
